-- Insert sample exercises
INSERT INTO exercises (name, category, difficulty, target_muscles, equipment, description, instructions, tips, variations)
VALUES
  ('Push-ups', 'upper_body', 'beginner', ARRAY['chest', 'shoulders', 'triceps'], ARRAY['none'], 
   'A classic bodyweight exercise that works multiple muscle groups simultaneously.',
   ARRAY['Start in a plank position with your hands slightly wider than shoulder-width apart.',
         'Lower your body until your chest nearly touches the floor.',
         'Push yourself back up to the starting position.',
         'Keep your body in a straight line throughout the movement.'],
   ARRAY['Keep your core engaged throughout the exercise.',
         'Don''t let your hips sag or pike up.',
         'For beginners, start with knee push-ups.',
         'For advanced, try diamond push-ups or decline push-ups.'],
   ARRAY['Wide Push-ups', 'Diamond Push-ups', 'Decline Push-ups', 'Incline Push-ups', 'One-arm Push-ups']),
   
  ('Squats', 'lower_body', 'beginner', ARRAY['quadriceps', 'hamstrings', 'glutes'], ARRAY['none', 'barbell', 'dumbbell'], 
   'A fundamental lower body exercise for building strength.',
   ARRAY['Stand with feet shoulder-width apart.',
         'Bend your knees and lower your hips as if sitting in a chair.',
         'Keep your chest up and back straight.',
         'Lower until thighs are parallel to the ground or as low as comfortable.',
         'Push through your heels to return to standing position.'],
   ARRAY['Keep your weight in your heels.',
         'Don''t let your knees cave inward.',
         'Maintain a neutral spine throughout the movement.',
         'Go as low as your mobility allows without compromising form.'],
   ARRAY['Goblet Squats', 'Back Squats', 'Front Squats', 'Split Squats', 'Pistol Squats']),
   
  ('Deadlifts', 'lower_body', 'intermediate', ARRAY['hamstrings', 'glutes', 'lower_back'], ARRAY['barbell', 'dumbbell'], 
   'A compound exercise that targets multiple muscle groups and builds overall strength.',
   ARRAY['Stand with feet hip-width apart, barbell over mid-foot.',
         'Bend at hips and knees to grip the bar with hands shoulder-width apart.',
         'Keep your back straight and chest up.',
         'Push through your heels and stand up straight, lifting the bar.',
         'Return the weight to the ground with controlled movement.'],
   ARRAY['Keep the bar close to your body throughout the movement.',
         'Engage your lats before lifting.',
         'Push the ground away rather than pulling the weight up.',
         'Don''t round your back.'],
   ARRAY['Romanian Deadlifts', 'Sumo Deadlifts', 'Single-leg Deadlifts', 'Trap Bar Deadlifts']),

  ('Plank', 'core', 'beginner', ARRAY['core', 'shoulders'], ARRAY['none'], 
   'An isometric core exercise that improves stability and posture.',
   ARRAY['Start in a push-up position.',
         'Lower to your forearms, keeping elbows under shoulders.',
         'Keep your body in a straight line from head to heels.',
         'Hold the position while breathing normally.'],
   ARRAY['Don''t let your hips sag or pike up.',
         'Keep your core tight throughout.',
         'Start with shorter holds and build up time.',
         'Focus on quality over duration.'],
   ARRAY['Side Plank', 'Plank Up-Downs', 'Plank with Leg Lifts', 'Mountain Climbers']),

  ('Pull-ups', 'upper_body', 'intermediate', ARRAY['lats', 'biceps', 'rhomboids'], ARRAY['pull-up bar'], 
   'A challenging upper body exercise that builds pulling strength.',
   ARRAY['Hang from a pull-up bar with hands slightly wider than shoulder-width.',
         'Pull your body up until your chin clears the bar.',
         'Lower yourself with control to the starting position.',
         'Keep your core engaged throughout.'],
   ARRAY['Start with assisted pull-ups if needed.',
         'Focus on controlled movement, not speed.',
         'Don''t swing or use momentum.',
         'Squeeze your shoulder blades together at the top.'],
   ARRAY['Chin-ups', 'Wide-grip Pull-ups', 'Assisted Pull-ups', 'Negative Pull-ups']),

  ('Lunges', 'lower_body', 'beginner', ARRAY['quadriceps', 'hamstrings', 'glutes'], ARRAY['none', 'dumbbell'], 
   'A unilateral lower body exercise that improves balance and strength.',
   ARRAY['Stand with feet hip-width apart.',
         'Step forward with one leg, lowering your hips.',
         'Lower until both knees are bent at 90 degrees.',
         'Push back to starting position and repeat on other side.'],
   ARRAY['Keep your torso upright throughout the movement.',
         'Don''t let your front knee go past your toes.',
         'Step far enough forward to maintain balance.',
         'Alternate legs or complete all reps on one side first.'],
   ARRAY['Reverse Lunges', 'Walking Lunges', 'Lateral Lunges', 'Jump Lunges']),

  ('Dips', 'upper_body', 'intermediate', ARRAY['triceps', 'chest', 'shoulders'], ARRAY['dip bars', 'chair'], 
   'An effective exercise for building tricep and chest strength.',
   ARRAY['Position yourself between parallel bars or on a chair.',
         'Lower your body by bending your elbows.',
         'Descend until you feel a stretch in your chest.',
         'Push back up to the starting position.'],
   ARRAY['Keep your body upright, don''t lean too far forward.',
         'Control the descent, don''t drop down quickly.',
         'Start with assisted dips if needed.',
         'Stop if you feel shoulder pain.'],
   ARRAY['Assisted Dips', 'Bench Dips', 'Ring Dips', 'Weighted Dips']),

  ('Burpees', 'full_body', 'intermediate', ARRAY['full_body'], ARRAY['none'], 
   'A high-intensity full-body exercise that combines strength and cardio.',
   ARRAY['Start standing, then squat down and place hands on floor.',
         'Jump feet back into plank position.',
         'Perform a push-up (optional).',
         'Jump feet back to squat position.',
         'Jump up with arms overhead.'],
   ARRAY['Move at your own pace, focus on form.',
         'Modify by stepping instead of jumping.',
         'Keep your core engaged throughout.',
         'Land softly to protect your joints.'],
   ARRAY['Half Burpees', 'Burpee Box Jumps', 'Single-arm Burpees', 'Burpee Pull-ups']);
